[parameters]
bbox = [[-0.5, 0.4975], [-0.25, 0.25]]  # computational domain
cfl  = 0.25
nx        = 400
ngh       = 0
nbuf      = 8
itlast    = 3200
out_every = 320
initial_data = "sinusoidal"
subcycling = false
# out_dir = "data"

[configs]
redirect_std = true
