[parameters]
bbox = [[-0.5, 0.49], [-0.25, 0.25]]  # computational domain
cfl  = 0.25
nx        = 100
ngh       = 0
nbuf      = 8
itlast    = 800
out_every = 80
initial_data = "sinusoidal"
subcycling = false
# out_dir = "data"

[configs]
redirect_std = true
