[parameters]
#bbox = [[-0.49875, 0.49875], [-0.25, 0.25]]  # computational domain
bbox = [[-0.5, 0.4975], [-0.25, 0.25]]  # computational domain
cfl  = 0.25
nx        = 400
ngh       = 0
nbuf      = 2
itlast    = 3200
out_every = 320
Mongwane  = true
apply_trans_zone = true
initial_data = "sinusoidal"
# out_dir = "data"

[configs]
redirect_std = true
