[parameters]
bbox = [[-0.5, 0.4975]]  # computational domain
cfl  = 0.25
nx        = 400
ngh       = 0
nbuf      = 2
itlast    = 1600
out_every = 160
initial_data = "sinusoidal"
# out_dir = "data"

[configs]
redirect_std = true
