[parameters]
bbox = [[-0.5, 0.495], [-0.25, 0.25]]  # computational domain
cfl  = 0.25
nx        = 200
ngh       = 0
nbuf      = 8
itlast    = 1600
out_every = 160
initial_data = "sinusoidal"
subcycling = false
# out_dir = "data"

[configs]
redirect_std = true
