[parameters]
bbox = [[-0.5, 0.49]]  # computational domain
cfl  = 0.25
nx        = 100
ngh       = 0
nbuf      = 2
itlast    = 400
out_every = 40
initial_data = "sinusoidal"
# out_dir = "data"

[configs]
redirect_std = true
